### ISSUE TITLE
Move terraform cloud to eu-west-1

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/ocf-infrastructure#160]
current terraform s3 state buckets are in eu-west-2, could they move to eu-west-1. All other things are int eu-west-1.

**Comment by devsjc** [comment]
I thought we used the terraform cloud remote backend - why is any state in s3 at all?

**Comment by peterdudfield** [comment]
im not sure, if you want to change it (and its easier, then please do)

**Comment by devsjc** [comment]
Is it the `nowcasting-terraform` and `sbri-terraform` buckets you are referring to? I'm not sure what state these hold, but it isn't the states for out current `nowcasting_development` and `nowcasting_production` workspaces. Their state is stored in terraform cloud (becasue our backend configuration in both cases is `remote` with the `app.terraform.io` hostname). There must have been some terraform written at some point with backend `s3` to have produced these. They've not been touched since the start and end of 2022 respectively - do you know what projects these were related to?

**Comment by peterdudfield** [comment]
Yea, delete them if they are not being used

**Comment by devsjc** [comment]
Cool, if you don't know what they're for then I can't imagine they are doing anything of value. Emptied and deleted!
