### ISSUE TITLE
Add auotmatic backups to rds database

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/ocf-infrastructure#90]
Add auotmatic backups to rds database

Perhaps start with backup every weeks on s3

two databases are here - https://github.com/openclimatefix/ocf-infrastructure/blob/main/terraform/modules/storage/database-pair/rds.tf

one more is here - https://github.com/openclimatefix/ocf-infrastructure/blob/main/terraform/modules/storage/postgres/rds.tf

**Comment by peterdudfield** [comment]
code is here https://github.com/openclimatefix/nowcasting_infrastructure/blob/main/terraform/modules/database/rds.tf

**Comment by BreakingPitt** [comment]
@peterdudfield 

Can you provide more information about this? 

The links doesn't seem to be valid so I've take a look at the modules inside this repo and seems that the configuration _backup_retention_period_ and _backup_window_ properties are defined on the aws_rds_resource inside the storage module.

So I guess that we are talking about the _database-pair_ module that doesn't have these configuration properties neither variables defined on it? 

I wonder why you didn't use Terraform modules available [here](https://github.com/terraform-aws-modules) instead of developing your own modules for the most generic components.

Best regards

**Comment by peterdudfield** [comment]
Good point @BreakingPitt, perhaos in the future it would be good to use those modules. It might be tricky to change over these without deleting data. 

Ive updated the links, so hopefully you can see where this code might be done. 

Thanks for helping out

**Comment by BreakingPitt** [comment]
@peterdudfield 

There is a new pull request, that addresses and fixes this problems. 

After seen the code I've decide to set a fixed value of 7 seven days for the 'backup_retention_period' property.

If you want a more customizable approach, I can take a look at the module to use variable values for the 'backup_retention_period' and 'backup_window' properties.

Best regards.
